apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mkqwoz07t-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mkqwoz07t-java-springboot-gitops